# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:x86_64-0.4.6
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
    volumes:
      - /data/fabric_backup/couchdb1:/opt/couchdb/data

  ca1:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c948492eeb4e0f00dfbb1a09aa01081cf81119a89cca8fc8ea629df723ea91cd_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c948492eeb4e0f00dfbb1a09aa01081cf81119a89cca8fc8ea629df723ea91cd_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - /data/fabric_backup/fabric-ca-server2:/etc/hyperledger/fabric-ca-server
    container_name: ca_peerOrg2

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.example.com
    depends_on:
      - couchdb1
  
  cli:
      container_name: cli2
      image: hyperledger/fabric-tools:x86_64-1.1.0
      tty: true
      environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_LOGGING_LEVEL=DEBUG
        - CORE_PEER_ID=cli
        - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
        - CORE_PEER_LOCALMSPID=Org2MSP
        - CORE_PEER_TLS_ENABLED=false
        - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      volumes:
          - /var/run/:/host/var/run/
          - /opt/goworkspace/src/github.com/hyperledger/fabric/examples/chaincode/go:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/go
          - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          - ./channel-artifacts/onechannel.tx:/opt/gopath/src/github.com/hyperledger/fabric/peer/onechannel.tx
      depends_on:
        - peer0.org2.example.com
